ALTER TABLE pending ADD COLUMN user_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pairs ADD COLUMN tg_owner_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pairs ADD COLUMN max_owner_id INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_pairs_tg_owner ON pairs(tg_owner_id);
